import { defineConfig, devices } from "@playwright/test";

// Spec C4 — responsive breakpoint contract. Every app must render correctly
// at each of these widths. Kept here (not in a shared file) because the
// Playwright config is the source of truth for the gate itself.
const RESPONSIVE_VIEWPORTS = [
  { name: "responsive-320-small-phone", viewport: { width: 320, height: 640 } },
  // 390 uses a real touch/mobile device profile per Spec C4 §D.1
  // ("at least one genuine mobile device profile — touch, not just a narrow desktop window").
  { name: "responsive-390-phone", device: devices["iPhone 12"] },
  { name: "responsive-768-tablet", viewport: { width: 768, height: 1024 } },
  { name: "responsive-1280-laptop", viewport: { width: 1280, height: 800 } },
  { name: "responsive-1920-desktop", viewport: { width: 1920, height: 1080 } },
] as const;

export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: "html",
  use: {
    baseURL: "http://localhost:3000",
    trace: "on-first-retry",
  },
  projects: [
    {
      name: "chromium",
      testDir: "./tests/e2e",
      use: { ...devices["Desktop Chrome"] },
    },
    {
      // Tenant-isolation project — spec: wiki/specs/stage0-tenant-isolation.md.
      // Kept as its own project so `test:isolation` runs only these specs and
      // `test:e2e` runs only the e2e smoke suite; both share the same webServer.
      name: "isolation",
      testDir: "./tests/isolation",
      use: { ...devices["Desktop Chrome"] },
    },
    {
      // Layout regression guardrail (card 2.3.51) — the BLOCKING layout gate.
      //
      // Its own project, next to the advisory Spec C4 one rather than folded
      // into it, because the two answer to different rulings: C4's suite is
      // advisory by CEO constraint and is not run by CI, this one fails the
      // build and runs on every push. Sharing a project would have made
      // flipping one of them blocking flip both.
      //
      // No viewport here: tests/layout/layout-guardrail.spec.ts declares its
      // own per width, so one run covers all three and the widths live next to
      // the assertions that use them.
      name: "layout-guardrail",
      testDir: "./tests/layout",
      use: { ...devices["Desktop Chrome"] },
      // Baselines are generated by CI and compared against CI (Playwright 1.60
      // installs no browser on the dev machine). Keeping `{platform}` in the
      // name is the safety catch: a baseline generated anywhere but Linux
      // lands in a different file, so it can never silently replace the one CI
      // compares against.
      snapshotPathTemplate: "{testDir}/__screenshots__/{arg}-{platform}{ext}",
      expect: {
        toHaveScreenshot: {
          // Same runner image, same browser build, so a clean run diffs at
          // zero. The 1% allowance absorbs sub-pixel antialiasing drift
          // without coming close to hiding the breakage this gate is for —
          // a nav that failed to switch arrangement, or a column ladder that
          // stopped laddering, moves far more of the picture than 1%.
          maxDiffPixelRatio: 0.01,
          animations: "disabled",
          caret: "hide",
        },
      },
    },
    // Spec C4 — multi-viewport advisory gate.
    // Every project runs the same responsive.spec.ts, so the single suite
    // executes five times, once per gated width.
    ...RESPONSIVE_VIEWPORTS.map((v) => ({
      name: v.name,
      testDir: "./tests/responsive",
      use:
        "device" in v
          ? { ...v.device }
          : { ...devices["Desktop Chrome"], viewport: v.viewport },
    })),
  ],
  webServer: {
    command: "npm run build && npm run start",
    url: "http://localhost:3000",
    reuseExistingServer: !process.env.CI,
    timeout: 120 * 1000,
    // CI-safe dummy values used when the environment has not already injected
    // them (local dev, stop-hook, or any runner that does not supply these).
    // These are the identical strings the CI workflow injects in its
    // "Playwright smoke test" step — no real secrets, no real systems reached.
    // process.env values already present always win (|| '' guard below ensures
    // an explicit empty string in the environment still gets the fallback).
    env: {
      AUTH_SECRET:
        process.env.AUTH_SECRET ||
        "ci-e2e-only-dummy-secret-not-used-anywhere-real",
      TENANCY_MODE: process.env.TENANCY_MODE || "per_tenant",
      DATABASE_URL: process.env.DATABASE_URL || "file:e2e-playwright.db",
      RATE_LIMIT_ALLOW_IN_MEMORY:
        process.env.RATE_LIMIT_ALLOW_IN_MEMORY || "true",
      STRIPE_SECRET_KEY:
        process.env.STRIPE_SECRET_KEY ||
        "sk_test_ci-e2e-only-dummy-not-a-real-key",
      STRIPE_WEBHOOK_SECRET:
        process.env.STRIPE_WEBHOOK_SECRET ||
        "whsec_ci-e2e-only-dummy-not-a-real-secret",
      APP_LIFECYCLE_STATE: process.env.APP_LIFECYCLE_STATE || "LAUNCHED",
      EMAIL_PROVIDER_API_KEY:
        process.env.EMAIL_PROVIDER_API_KEY ||
        "re_ci-e2e-only-dummy-not-a-real-key",
      EMAIL_SEND_MODE: process.env.EMAIL_SEND_MODE || "log",
    },
  },
});
