import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/* ── THE RESPONSIVE FOUNDATION (card 2.3.15) ──────────────────────────────────
 *
 * Read docs/responsive.md before writing UI code. The short version:
 *
 *   COMPONENTS ASK THEIR CONTAINER, PAGES ASK THE VIEWPORT.
 *   A component that reflows on `md:` is guessing — it assumes it occupies the
 *   whole viewport, and it breaks the moment somebody drops it in a sidebar, a
 *   two-column grid, or a modal. Container variants (`@sm:`, `@md:`, `@[30rem]:`)
 *   ask the only question that is actually answerable locally: how much room do
 *   *I* have? Viewport media queries (`sm:`, `md:`) are reserved for the
 *   top-level page skeleton, which genuinely is the viewport.
 *
 *   TYPE AND SPACING ARE FLUID, NOT STEPPED.
 *   `fluid()` below emits a clamp() that interpolates smoothly between a small
 *   and a large viewport, so there is no snap at a breakpoint and no need to
 *   restate a size at every screen width.
 *
 * WHY THIS LIVES HERE AND NOT IN globals.css: agents/build-init.py OVERWRITES
 * app/globals.css with the generator's output for every new app, but never
 * touches this file. A scale defined as custom properties in globals.css would
 * silently vanish from every generated product. Defined here, it is inherited.
 *
 * This layer is ADDITIVE. Every existing `sm:`/`md:` class keeps working exactly
 * as before; nothing was removed.
 */

/** The viewport range the fluid scale interpolates across, in px. */
const FLUID_MIN_VW = 320;
const FLUID_MAX_VW = 1280;

/**
 * A smoothly interpolating size.
 *
 * `minPx` is the size at a 320px viewport, `maxPx` the size at 1280px. Between
 * them the value tracks the viewport linearly; outside them it is clamped.
 *
 * ── THE CEILING IS A ZOOM ALLOWANCE, NOT A DESIGN SIZE (WCAG 1.4.4) ─────────
 * The obvious way to write this is `clamp(min, fluid, max)` with `max` set to
 * the intended large-screen size. That quietly breaks text resizing: the `vw`
 * term does not grow when a user raises their browser's font size, so the rem
 * terms grow, hit `max`, and stop. Text that must reach 200% caps out far below
 * it, and the failure is invisible to anyone not testing at zoom.
 *
 * So the third argument is NOT the design size — it is `2 x minPx`, pure
 * headroom, and `assertZoomHeadroom` refuses any step where the design size
 * would collide with it. At a 1280px viewport the middle term is what renders
 * (that is the design size); the ceiling only ever binds once the user has
 * zoomed, which is precisely when it should stop binding.
 */
function fluid(minPx: number, maxPx: number): string {
  assertZoomHeadroom(minPx, maxPx);
  const slope = (maxPx - minPx) / (FLUID_MAX_VW - FLUID_MIN_VW);
  const interceptRem = (minPx - slope * FLUID_MIN_VW) / 16;
  const vw = +(slope * 100).toFixed(4);
  const round = (n: number) => +n.toFixed(4);
  return `clamp(${round(minPx / 16)}rem, ${round(interceptRem)}rem + ${vw}vw, ${round((minPx * 2) / 16)}rem)`;
}

/** A step whose large-screen size is at or above its own zoom ceiling would be
 *  clipped at wide viewports — a design bug and an accessibility one at once.
 *  Fail the build rather than ship a size that silently renders too small. */
function assertZoomHeadroom(minPx: number, maxPx: number): void {
  if (maxPx > minPx * 2) {
    throw new Error(
      `fluid(${minPx}, ${maxPx}): the large size exceeds the 2x zoom ceiling ` +
        `(${minPx * 2}px). Raise the min or lower the max — do not raise the ` +
        `ceiling, which is what keeps text resizable to 200% (WCAG 1.4.4).`,
    );
  }
}

const config: Config = {
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    // `lib/` is scanned too (card 2.3.50). Class names now live there —
    // lib/table/responsive-columns.ts holds the column-priority classes — and
    // Tailwind only emits a class it has literally seen. Leave lib/ out and the
    // rule is defined, imported, applied to the element, and produces no CSS:
    // no error, no warning, the column just never comes back. A test pins this
    // glob to that file so the two cannot drift apart.
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      // All colours reference CSS custom properties — never hardcode values here.
      // Token values live in app/globals.css and are generated by build-design.py.
      //
      // COLOUR FORMAT CONTRACT — hsl(var(--token)) wrapping a CHANNEL TRIPLET.
      // The tokens in globals.css hold bare HSL channels ("224.3 76.3% 48%"),
      // NOT hex, and every mapping here wraps them in hsl(). The two halves are
      // one decision: a hex token under this mapping yields hsl(#1d4ed8), which
      // is invalid CSS and renders nothing at all.
      //
      // Why not the simpler `var(--primary)` holding hex (the previous scheme):
      // Tailwind cannot inject an alpha channel into an already-opaque value, so
      // every opacity modifier — bg-primary/50, ring-accent/20 — was SILENTLY
      // DROPPED. No rule was emitted, the colour simply did not apply, and
      // nothing warned. Measured, not assumed: under the old mapping a build
      // containing bg-primary/50 emitted zero bytes for it; under this one it
      // emits `hsl(var(--primary) / 0.5)`. tests/unit/design-tokens.test.ts pins
      // that so the regression cannot come back.
      //
      // This is also the convention shadcn/ui's own Tailwind v3 template uses,
      // so components copied in from it work against these tokens unmodified.
      // The DEFAULT/foreground nesting is shadcn's shape. `bg-primary` still
      // resolves via DEFAULT exactly as before, and `text-primary-foreground`
      // becomes available for components that need the paired text colour.
      //
      // ONE SEMANTIC COLLISION TO KNOW ABOUT, for card 2.3.3 (the seed):
      // shadcn uses `--accent` for a SUBDUED hover background (its own default
      // is roughly slate-100), with dark --accent-foreground text on it. In
      // this palette --accent is a VIVID brand colour. We keep our meaning,
      // because generated apps already use accent as a brand fill and changing
      // it would break them. The consequence is that shadcn components which
      // use `bg-accent` for hover states (dropdown items, command menus,
      // calendar cells) will render a vivid hover instead of a subtle one.
      // Fix at seed time by changing those copied components to `bg-muted` —
      // a one-word edit per component, and cheap precisely because copy-in
      // means we own the source. Do NOT "fix" it by redefining --accent.
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        surface: "hsl(var(--surface))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        link: "hsl(var(--link))",
        "text-primary": "hsl(var(--text-primary))",
        "text-secondary": "hsl(var(--text-secondary))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
      },
      // --radius is a LENGTH, so it is used bare — never hsl()-wrapped.
      // lg resolves to 0.5rem and md to 0.375rem, both identical to Tailwind's
      // defaults, so nothing already built changes shape. sm moves from
      // 0.125rem to 0.25rem; `rounded-sm` is unused in this template.
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },

      /* ── Fluid type ────────────────────────────────────────────────────────
         Added ALONGSIDE Tailwind's own scale, never replacing it: `text-sm`,
         `text-lg` and friends are untouched, so nothing already built shifts.
         Reach for `text-fluid-*` in new UI. The pairs are (size at 320px, size
         at 1280px); each stays inside its 2x zoom ceiling — see fluid(). */
      fontSize: {
        "fluid-xs": [fluid(13, 14), { lineHeight: "1.5" }],
        "fluid-sm": [fluid(14, 15), { lineHeight: "1.5" }],
        "fluid-base": [fluid(16, 18), { lineHeight: "1.6" }],
        "fluid-lg": [fluid(18, 21), { lineHeight: "1.5" }],
        "fluid-xl": [fluid(21, 25), { lineHeight: "1.4" }],
        "fluid-2xl": [fluid(25, 31), { lineHeight: "1.3" }],
        "fluid-3xl": [fluid(30, 42), { lineHeight: "1.2" }],
        "fluid-4xl": [fluid(35, 56), { lineHeight: "1.1" }],
      },

      /* ── Fluid spacing ─────────────────────────────────────────────────────
         Usable anywhere Tailwind takes a spacing value — p-, m-, gap-, space-.
         Same additive rule: the numeric scale (p-4, gap-2) still works. */
      spacing: {
        "fluid-3xs": fluid(4, 5),
        "fluid-2xs": fluid(8, 10),
        "fluid-xs": fluid(12, 16),
        "fluid-sm": fluid(16, 21),
        "fluid-md": fluid(24, 32),
        "fluid-lg": fluid(32, 42),
        "fluid-xl": fluid(48, 64),
        "fluid-2xl": fluid(64, 96),
      },

      /* ── Named container sizes ─────────────────────────────────────────────
         The plugin ships @sm…@7xl already. These name the two boundaries this
         template actually reasons about, so a component says WHY it rearranges
         rather than restating a magic number:
           compact — below this a horizontal row of controls stops fitting
           roomy   — at or above this there is room for a side-by-side layout */
      containers: {
        compact: "24rem", // 384px
        roomy: "40rem", // 640px
      },
    },
  },
  plugins: [forms, containerQueries],
};

export default config;
