import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";

const config: Config = {
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      // All colours reference CSS custom properties — never hardcode values here.
      // Token values live in app/globals.css and are generated by build-design.py.
      //
      // COLOUR FORMAT CONTRACT — hsl(var(--token)) wrapping a CHANNEL TRIPLET.
      // The tokens in globals.css hold bare HSL channels ("224.3 76.3% 48%"),
      // NOT hex, and every mapping here wraps them in hsl(). The two halves are
      // one decision: a hex token under this mapping yields hsl(#1d4ed8), which
      // is invalid CSS and renders nothing at all.
      //
      // Why not the simpler `var(--primary)` holding hex (the previous scheme):
      // Tailwind cannot inject an alpha channel into an already-opaque value, so
      // every opacity modifier — bg-primary/50, ring-accent/20 — was SILENTLY
      // DROPPED. No rule was emitted, the colour simply did not apply, and
      // nothing warned. Measured, not assumed: under the old mapping a build
      // containing bg-primary/50 emitted zero bytes for it; under this one it
      // emits `hsl(var(--primary) / 0.5)`. tests/unit/design-tokens.test.ts pins
      // that so the regression cannot come back.
      //
      // This is also the convention shadcn/ui's own Tailwind v3 template uses,
      // so components copied in from it work against these tokens unmodified.
      colors: {
        primary: "hsl(var(--primary))",
        secondary: "hsl(var(--secondary))",
        background: "hsl(var(--background))",
        surface: "hsl(var(--surface))",
        "text-primary": "hsl(var(--text-primary))",
        "text-secondary": "hsl(var(--text-secondary))",
        border: "hsl(var(--border))",
        accent: "hsl(var(--accent))",
        destructive: "hsl(var(--destructive))",
        link: "hsl(var(--link))",
      },
    },
  },
  plugins: [forms],
};

export default config;
