/**
 * The layout guardrail (card 2.3.51).
 *
 * Three cards built the layout of this template: container queries and fluid
 * type as the default build path (2.3.15), one responsive nav (2.3.49), one
 * responsive data table (2.3.50). Nothing stops the next feature quietly
 * undoing any of it. This file is what stops it: it runs in CI on every push
 * and FAILS THE BUILD when a page starts scrolling sideways or its layout
 * shifts away from a committed picture of itself.
 *
 * ── THE TWO CHECKS, AND WHY THEY ARE DIFFERENT KINDS OF CHECK ──────────────
 *
 *   1. NO HORIZONTAL OVERFLOW — the hard gate.
 *      `document.documentElement.scrollWidth <= document.documentElement.clientWidth`.
 *      Deterministic, needs no baseline, and cannot produce a false failure:
 *      either the document is wider than the space it has or it is not. This
 *      is the failure that actually ruins a screen — a wide element pushes the
 *      DOCUMENT sideways, the fixed bottom tab bar slides off, and every other
 *      element on the page is laid out against something wider than the phone.
 *
 *   2. THE LAYOUT MATCHES ITS BASELINE — the diff.
 *      A committed screenshot per page per width. It catches the breakage the
 *      overflow assertion cannot see: a nav that stopped switching to its bar
 *      arrangement, a table that lost its column ladder, a section that
 *      collapsed to zero height. It cannot say whether a layout is GOOD, only
 *      whether it CHANGED, which is exactly the job — an intended change is
 *      one baseline regeneration away (docs/layout-guardrail.md).
 *
 * "Fits, but cramped" is deliberately NOT gated here. That is a human glance.
 * Asserting aesthetic quality with a machine produces a gate people learn to
 * ignore, which is worse than no gate.
 *
 * ── WHY THIS IS ITS OWN PROJECT AND ITS OWN CI STEP ────────────────────────
 * tests/responsive/ (Spec C4) already visits five widths, but it is ADVISORY
 * by CEO ruling and CI does not run it at all. This suite is the opposite: a
 * narrow, blocking gate. Keeping them apart means flipping this one to
 * blocking did not silently make the touch-target and axe checks blocking too.
 * It also needs its own env — APP_LIFECYCLE_STATE=LAUNCHED, because the pages
 * worth guarding are behind sign-in and LIVE_EVAL 403s a fresh CI user off
 * /dashboard (lib/live-eval.ts).
 *
 * ── WHY IT ONLY EVER RUNS IN CI ────────────────────────────────────────────
 * Playwright 1.60 cannot install a browser on the dev machine (no Ubuntu 26.04
 * support), so the baselines are generated by CI and compared against CI. A
 * baseline made anywhere else differs in font rasterisation and every run after
 * it fails. The regeneration path is a workflow, not a local command:
 * .github/workflows/layout-baselines.yml. See docs/layout-guardrail.md.
 */

import { test, expect, type Page } from "@playwright/test";

/**
 * The widths.
 *
 * The card asked for 375 / 768 / 1280. 375 is not a gated width anywhere in
 * this system: the breakpoint contract (Spec C4, playwright.config.ts) is
 * 320 / 390 / 768 / 1280 / 1920, and 320 is the width Spec C4 calls "the floor
 * — where layouts actually break". So the phone leg is 320: strictly harder
 * than 375, and on-contract rather than beside it. Tablet and desktop are the
 * carded widths unchanged.
 *
 * Three widths, not all five, is the card's cost discipline — each width is a
 * sign-up, two page loads and two full-page screenshots. Adding 390 or 1920
 * later is one line here plus a baseline regeneration.
 */
const WIDTHS = [
  { label: "phone", width: 320, height: 640 },
  { label: "tablet", width: 768, height: 1024 },
  { label: "desktop", width: 1280, height: 800 },
] as const;

/**
 * The pages.
 *
 * Two, not every route — the card is explicit that this is not a screenshot of
 * the whole app. These two are the ones that exercise what the layout run
 * built: both carry the primary nav (rendered by their segment layouts), and
 * they are the surfaces every app inherits. A descendant app extends this list
 * with its own screens; K9Coach's /dashboard is the same path carrying a real
 * data table.
 */
const PAGES = [
  { name: "dashboard", path: "/dashboard" },
  { name: "account", path: "/account" },
] as const;

/**
 * A FIXED name, deliberately.
 *
 * /dashboard renders `session.user.name ?? session.user.email`. A generated
 * email would put a different string on the page every run — and a different
 * LENGTH of string, which at 320px is a different number of wrapped lines and
 * therefore a genuinely different layout. Supplying a name (the signup form's
 * optional third field) makes the greeting a constant, so the baseline is
 * comparing layout rather than noise. This is the fix; masking the greeting
 * would only hide the symptom.
 */
const ACCOUNT_NAME = "Layout Guardrail";
const PASSWORD = "GuardrailPass123!secure";

/**
 * One account per width, and the addresses are all the SAME LENGTH — padded to
 * four digits. Different widths need different accounts (they run as separate
 * tests and each signs in), but a 320-vs-1280 difference in the address is a
 * difference in the rendered page if it ever reaches one.
 */
function emailFor(width: number): string {
  return `layout-guardrail-${String(width).padStart(4, "0")}@house-starter.test`;
}

/**
 * Get to a signed-in dashboard.
 *
 * Signs up, and falls back to signing in when the account already exists. That
 * second path is not hypothetical: CI retries a failed test once, and the retry
 * runs against the same database the first attempt wrote to. Without the
 * fallback every retry would fail on "email already registered" and report a
 * layout regression that is really a duplicate-account error.
 */
async function signInAtDashboard(page: Page, width: number): Promise<void> {
  const email = emailFor(width);

  await page.goto("/signup");
  // The field's accessible name is "Name (optional)", so anchor the match at
  // the start rather than matching "name" loosely anywhere on the form.
  await page.getByLabel(/^Name/).fill(ACCOUNT_NAME);
  await page.getByLabel("Email", { exact: true }).fill(email);
  await page.getByLabel("Password", { exact: true }).fill(PASSWORD);
  await page.getByRole("button", { name: /create account/i }).click();

  const signedUp = await page
    .waitForURL("/dashboard", { timeout: 20_000 })
    .then(() => true)
    .catch(() => false);
  if (signedUp) return;

  await page.goto("/login");
  await page.getByLabel("Email", { exact: true }).fill(email);
  await page.getByLabel("Password", { exact: true }).fill(PASSWORD);
  await page.getByRole("button", { name: /sign in/i }).click();
  await page.waitForURL("/dashboard");
}

/** The measurement the whole gate turns on. */
async function documentWidths(
  page: Page,
): Promise<{ scroll: number; client: number }> {
  return await page.evaluate(() => ({
    // clientWidth, NOT window.innerWidth. innerWidth includes the vertical
    // scrollbar, so a document exactly as wide as innerWidth is already
    // overflowing by the scrollbar's width and this check would call it clean.
    // Spec C4's advisory suite compares against innerWidth; this one is
    // deliberately the stricter of the two.
    scroll: document.documentElement.scrollWidth,
    client: document.documentElement.clientWidth,
  }));
}

for (const { label, width, height } of WIDTHS) {
  test.describe(`${label} — ${width}px`, () => {
    test.use({ viewport: { width, height } });
    // A sign-up plus two page loads and two full-page screenshots.
    test.setTimeout(120_000);

    test("no horizontal overflow, and the layout matches its baseline", async ({
      page,
    }) => {
      await signInAtDashboard(page, width);

      for (const target of PAGES) {
        await test.step(`${target.path} at ${width}px`, async () => {
          await page.goto(target.path);

          // Wait for the thing both pages have in common rather than a
          // networkidle guess: if the nav is on screen, the segment layout has
          // rendered and there is something real to measure.
          await expect(
            page.getByRole("navigation", { name: "Primary" }),
          ).toBeVisible();

          // ── GATE 1: the document does not scroll sideways. ───────────────
          const { scroll, client } = await documentWidths(page);
          expect(
            scroll,
            `${target.path} at ${width}px scrolls sideways: the document is ` +
              `${scroll}px wide inside ${client}px — ${scroll - client}px of ` +
              `horizontal overflow. Something on this page is wider than the ` +
              `space it was given.`,
          ).toBeLessThanOrEqual(client);

          // ── GATE 2: the layout still looks like its committed baseline. ──
          // Checked second on purpose: when both fail, the failure people read
          // first is the one that names the actual problem.
          await expect(page).toHaveScreenshot(`${target.name}-${width}.png`, {
            fullPage: true,
          });
        });
      }
    });
  });
}
